# source common.sh >> source is not required in ansible, only CONSIDER shell_functions
source common.sh

# 1.----------------------------------------------------------------------------------------------
PRINT_HEAD "install redis repos"
yum install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y  &>> /tmp/roboshop.log
STATUS_CHECK

- name: install redis repos & enable redis
  Ansible.builtin.shell: {{item}}
  loop:
     - yum install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
     - dnf module enable redis:remi-6.2 -y

PRINT_HEAD "enable redis "
dnf module enable redis:remi-6.2 -y  &>> /tmp/roboshop.log
STATUS_CHECK


# 2.--------------------------------------------------------------------------------------------------
PRINT_HEAD "install redis "
yum install redis -y  &>> /tmp/roboshop.log
STATUS_CHECK

- name: install redis
  ansible.builtin.yum:
    name: redis
    state: installed

# 3.-----------------------------------------------------------------------------------------------
PRINT_HEAD " Update listen address from 127.0.0.1 to 0.0.0.0 in /etc/redis.conf"
sed -i -e 's/127.0.0.1/0.0.0.0/' /etc/redis.conf  &>> /tmp/roboshop.log
STATUS_CHECK

- name: Update listen address from 127.0.0.1 to 0.0.0.0 in /etc/redis.conf & in /etc/redis/redis.conf
  ansible.builtin.lineinfile: {{item}}
    path:
       loop:
          - /etc/redis.conf
          - /etc/redis/redis.conf
    regexp: '127.0.0.1'
    line: 0.0.0.0

PRINT_HEAD " Update listen address from 127.0.0.1 to 0.0.0.0 in /etc/redis/redis.conf"
sed -i -e 's/127.0.0.1/0.0.0.0/' /etc/redis/redis.conf  &>> /tmp/roboshop.log
STATUS_CHECK

# 4.-----------------------------------------------------------------------------------------------------
PRINT_HEAD " enable redis "
systemctl enable redis   &>> /tmp/roboshop.log
STATUS_CHECK
-
- name: start redis (including enable & restart)
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: true

PRINT_HEAD " start redis "
systemctl start redis  &>> /tmp/roboshop.log
STATUS_CHECK









