# component=mongod >> in vars.yml >> component: mongod

# source common.sh >> source is not required in ansible, only CONSIDER shell_functions

# 1.--------------------------------------------------------------------------------------------
PRINT_HEAD "Setup the MongoDB repo file"
cp ${path}/files/mongo.repo /etc/yum.repos.d/mongo.repo  &>> /tmp/roboshop.log
STATUS_CHECK

- name: Setup the MongoDB repo file
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

# 2.---------------------------------------------------------------------------------------
PRINT_HEAD "install mongodb"
yum install mongodb-org -y  &>> /tmp/roboshop.log
STATUS_CHECK

- name: install mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

# 3.--------------------------------------------------------------------------------------
PRINT_HEAD "Update listen address from 127.0.0.1 to 0.0.0.0"
sed -i -e 's/127.0.0.1/0.0.0.0/' /etc/{{component}}.conf  &>> /tmp/roboshop.log
STATUS_CHECK

- name: Update listen address from 127.0.0.1 to 0.0.0.0
  ansible.builtin.lineinfile:
    path: /etc/{{component}}.conf
    regexp: '127.0.0.1'
    line: 0.0.0.0

# 4.----------------------------------------------------------------------------------
- name: start mongodb
  ansible.builtin.systemd:
    name: mongodb
    state: restarted
    enabled: true

PRINT_HEAD "enable mongodb"
systemctl enable {{component}}   &>> /tmp/roboshop.log
STATUS_CHECK

PRINT_HEAD "start mongodb"
systemctl start {{component}}  &>> /tmp/roboshop.log
STATUS_CHECK

PRINT_HEAD "restart mongodb"
systemctl restart {{component}}   &>> /tmp/roboshop.log
STATUS_CHECK

