# component=dispatch >> in vars.yml >> component: dispatch

# source common.sh >> source is not required in ansible, only CONSIDER shell_functions

# 1.--------------------------------------------------------------------------------------------------
PRINT_HEAD "install golang"
yum install golang -y  &>> /tmp/roboshop.log
STATUS_CHECK

- name: install golang
  ansible.builtin.yum:
    name: golang
    state: installed

# 2.------------------------------------------------------------------------------------------------
APP_PREREQ

# APP_PREREQ is a shell_function
- name: Importing Common role (app_prereq)
  ansible.builtin.import_role:
    name: common
    tasks_from: app_prereq  #(".yml" extension shall be ignored while importing role)

# 3.------------------------------------------------------------------------------------------------
PRINT_HEAD "Download Dependencies"
cd /app  &>> /tmp/roboshop.log
go mod init dispatch &>> /tmp/roboshop.log
go get  &>> /tmp/roboshop.log
go build &>> /tmp/roboshop.log
STATUS_CHECK

# installing package in target directory
- name: Download Dependencies in /app_directory
  ansible.builtin.shell: {{item}}
    loop:
      - go mod init dispatch
      - go get
      - go build
    args:
      chdir: /app

# 4.--------------------------------------------------------------------------------------------
systemd_setup

# systemd_setup is a shell_function
- name: Importing Common role (systemd_setup)
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd_setup  #(".yml" extension shall be ignored while importing role)
