  NODEJS() {
    PRINT_HEAD "Setup NodeJS repos"
    curl -sL https://rpm.nodesource.com/setup_lts.x | bash  &>> /tmp/roboshop.log
    STATUS_CHECK
    
    PRINT_HEAD "Install NodeJS"
    yum install nodejs -y &>> /tmp/roboshop.log
    STATUS_CHECK
  }

# 1.--------------------------------------------------------------------------------------------
- name: Setup NodeJS repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

# 2.-------------------------------------------------------------------------------------
- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

